### ISSUE TITLE
This functionality isn't really truly necessary to access original-behavior stuff, if you cache -- and it's hard to use regardless

### ISSUE THREAD

**Issue by jswalden** [domenic/get-originals#13]
(This is more meta-issue than issue, and it meanders sometimes because it's about fundamental things.  But I don't know a good way to raise fundamental issues other than with an issue.  So, here.)

The proposal posits that

> invoking these underlying operations is not an ability currently available to web developers. Thus, invoking them violates the layered API constraint of not using any un-layered magic.

This is not really true.  Every bit of original-operation behavior and identity one might want, _can_ be cached for subsequent use -- you just need to be able to run some bit of JS before anything else has run.  So for example, Mozilla's own JS tests use this trick to [https://searchfox.org/mozilla-central/source/js/src/tests/shell.js](implement) various test-harness functions, in a manner such that the tests themselves can't break the harness.  (At least theoretically -- I doubt every single aspect of that file is correct in this sense, which is largely fine for our purposes.)

Admittedly, this is not _quite_ a solution for multiple libraries, all existing together, that want to access original functionality.  For that, one might argue you maybe _do_ need exactly the functionality this proposal wants.  (But I certainly can imagine alternative tactics: make instantiating the library require calling a function, and you pass in certain primordial values to use within it, that you don't want to be muck-aroundable.)

But given how very, very difficult it is to write JS that _doesn't_ implicitly depend on characteristics of the external environment -- for example, try writing resilient code that does search-and-replace on a string!  or anything at all about regular expressions -- I am not convinced this is a problem you can just immediately declare as solved, by providing this API and expecting that people will capably and correctly and 100% perfectly using it.  SpiderMonkey and v8 both have self-hosted code in them to implement the standard library.  We have both had a noticeable number of cases where our implementations of fairly basic spec algorithms, could be improperly affected by user-defined code.  We know what we're doing (mostly), but _even still_ we screw this up.

At a foundational level, I'm not all that certain this is a problem that _needs_ solving, if it's for spec purity purposes.  Specs can enumerate their own entrypoints, perhaps in a stylistically consistent fashion (arguably this should be done regardless), to provide similar capability.  And if it's for library purposes, 1) this functionality is extremely difficult to use correctly, and if that's set aside 2) libraries do have options if they can run some trusted code to cache values for future use, and if they can't 3) libraries could have init functions that _accept_ those trusted values and then keep them cached internally, if we're concerned about multiple libraries playing well together.

**Comment by benjamingr** [comment]
Thanks for bringing "who are the consumers" up.

At Node.js we are definitely interested in this proposal and potentially implementing it for save JS built ins and as a clear and concise way to get original values.

So, this is a problem _we need solving_ and doing it differently has a lot of overhead for us. I realise we can grab out own builtins by running first - but doing this correctly and safely is not obvious.

As we consider "tamper proofing" core spec help is much appreciated.

**Comment by domenic** [comment]
> you just need to be able to run some bit of JS before anything else has run

@jswalden right, this proposal is specifically geared at cases where you aren't running first. I guess I should make that clearer in the README.

>  am not convinced this is a problem you can just immediately declare as solved, by providing this API and expecting that people will capably and correctly and 100% perfectly using it. 

That's definitely not the intent. For one, we're investing heavily in tools that will audit and potentially rewrite code to use this functionality, to help with this. But even then, we think it's important to provide the capability, even if using it correctly will require care.

> At a foundational level, I'm not all that certain this is a problem that needs solving, if it's for spec purity purposes. Specs can ... And if it's for library purposes...

I'm not sure how much you dug into the "Motivation" section in this proposal, but we're hoping to use this as a foundation for layered APIs, which are specs that *cannot* enumerate their own entrypoints, since they are constrained to not do anything magic (like always running first) which author code cannot do.

**Comment by jswalden** [comment]
> For one, we're investing heavily in tools that will audit and potentially rewrite code to use this functionality, to help with this. But even then, we think it's important to provide the capability, even if using it correctly will require care.

@domenic That at least is mildly comforting, tho given the loose typing of JS I'm not sure how far it really gets you.  There are the particularly fraught things like search-and-replace as previously mentioned, or even things one might think would be safe like `[].push`.  Not to mention sometimes you might want to invoke original behaviors that _do_ depend on user modifications to things, meaning that "not at all user-affectable" and "user-affectable" is not a workable distinction between desired and undesired semantics.

> I'm not sure how much you dug into the "Motivation" section in this proposal, but we're hoping to use this as a foundation for layered APIs, which are specs that cannot enumerate their own entrypoints, since they are constrained to not do anything magic (like always running first) which author code cannot do.

Maybe I don't understand terminology well enough here -- I assumed reading that, that specs "running" was meant in something like an abstract-interpretation sense.  Is "spec" some bit of Node lingo about actual runnable code that people run?  'cause otherwise, like, HTML spec and similar can just deep-call to things like `ArraySpeciesCreate` by name and spec-linking and similar however they need to define whatever incorruptible behavior they want.

**Comment by bzbarsky** [comment]
I think the issue is that "layered APIs" are APIs that are supposed to be perfectly polyfillable (and come with built-in fallback to a polyfill).  Which means one needs to be able to build that polyfill...

**Comment by domenic** [comment]
> That at least is mildly comforting, tho given the loose typing of JS I'm not sure how far it really gets you.

We have a few ideas, [some sketched in the readme](https://github.com/domenic/get-originals#automatic-rewritingenforcement-of-robustness). I see two basic approaches: (1) be over-conservative in what is disallowed, e.g. some variation of "do not allow dot access"; (2) write your library in a type-safe language that compiles to JavaScript (e.g. TypeScript, or perhaps some soundly-typed variant or subset of it). We'll definitely keep you updated, and appreciate some of the specific difficulties you mention.

As for how layered API specs are different, @bzbarsky's explanation is a good one. Another perspective is that "deep-call to things like ArraySpeciesCreate by name" and "whatever incorruptible behavior they want" are magic capabilities not accessible to web developers today, which we don't want to use inside layered API specifications.

**Comment by bzbarsky** [comment]
I will be honest: "we don't want to use" is an argument from theoretical purity, which in the priority of constituencies is dead last.

The argument that having perfectly polyfillable APIs is good is an argument from "needs of authors", assuming this is a need authors actually have (do they?).  That carries a lot more weight with me, if this is an actual author need.

It's worth keeping in mind that @jswalden is coming from a place of spending a fair amount of time writing JS in the kind of environment where one has primitives akin to the ones being proposed here, manipulating untrusted objects.  Even with serious static tooling support (which also exists; for example "do not allow dot access" is definitely enforced in that environment) it's a fairly miserable and failure-prone experience.  And the ergonomics in that environment are somewhat superior to the ones being proposed here, not least because it's possible to change it to expose things in more ergonomic ways as needed.

**Comment by domenic** [comment]
Sure, I can see how that phrasing would make it sound like it was motivated by theoretical purity, sorry. I was using it more as a shorthand for the whole host of concerns outlined in https://extensiblewebmanifesto.org/, which might still seem theoretical, but are definitely grounded in author pain and desires. We have indeed seen a lot of pain from the inability to create faithful polyfills for high-level features, and this is part of the program of alleviating that pain.

**Comment by jorendorff** [comment]
IIUC, the user story here is like:

* I need to mutate globals, which is necessary and good

* My problem is other scripts may have mutated all the globals, but in a problematic way

The two parts of this story are the same thing, right? The call is coming from inside the house.

Maybe global-mutating polyfills kind of inherently have this drawback. Can we address that? Provide better ways for scripts/modules to control the environment they run in, so that they "see" only polyfills/monkeypatches that they opted in to see?

Of course that's a much bigger lift than `GetOriginals`. But it feels like `GetOriginals` is addressing the pain of a very narrow constituency—people writing polyfills; or, people who can afford to rewrite their code in a custom originals-using language variant and compile that to JS—when the same problem affects all application code.

**Comment by ljharb** [comment]
Narrower than that - that constituency, but only when they can’t run some part of their code first (to robustly cache references to the originals prior to other code running)
